### ISSUE TITLE
Java 7 / Android client support

### ISSUE THREAD

**Issue by ChakshuGautam** [FusionAuth/fusionauth-java-client#2]
I am facing the following error
`Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZonedDateTime;`

The environment is android and it would be really helpful if you could guide me the path of least changes to fix this for Java 7. I would want to uses the Models classes in Java Client and even the serialisers and deserialisers but currently they are dependent on JacksonModule.

**Comment by robotdan** [comment]
In theory we could build a Java 7 version of the client, or probably better named an Android client. 

The `ZonedDateTime` object is serialized to a long - milliseconds in UTC. So you can make that field type anything you want as long as when you send it across the wire it is milliseconds in UTC. 

https://fusionauth.io/docs/v1/tech/reference/data-types  - see Instants. 

If you're interested in contributing to build an Android client, I can bootstrap it let you hack on it. What does Android provide for JSON support? The current java client uses Jackson heavily.

**Comment by ChakshuGautam** [comment]
I would be more than happy to contribute considering I am using this so much. A bootstrap should be really helpful. [GSON](https://github.com/google/gson) is the most popular library for Android. Can be used for Java 7 as well.

**Comment by robotdan** [comment]
Great, I'll add some links to this issue once I get it set up for you to mess with .

**Comment by ChakshuGautam** [comment]
Let me know when you create the repo. I was free for a couple of days next weekend and it would great working on this.

**Comment by robotdan** [comment]
I've started a stub repo. 

https://github.com/FusionAuth/fusionauth-android-client

See if you can follow the instructions from the client builder repo to get started.
https://github.com/FusionAuth/fusionauth-client-builder

Here is the template for the Android client:
https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/client/android.client.ftl

When you run the build command  `sb build-android` it will use that template to build the client library.
https://github.com/FusionAuth/fusionauth-android-client/blob/master/src/main/java/io/fusionauth/client/FusionAuthClient.java

You can start by cloning the `fusionauth-client-builder` and `fusionauth-android-client` repos and then start hacking, and then feel free to submit a PR once you've got something working. 

The Android template is just a copy from Java, so you'll essentially just need to remove any Java 8 features such as lambdas. I don't know much about the Android SDK, so if you can't use Jackson then you'll need to rip that and replace it with another JSON library.

I would say to start, just copy over a minimal set of domain objects to get it working. (such as User, Application etc). We are working on a way to build out the domain from a JSON DSL, so once that is ready we can use that to build out the Android domain objects so you don't have to do it manually. 

You can ask any questions you have here, or feel free to join the slack channel as well.

**Comment by robotdan** [comment]
Closing, moved to feature. https://github.com/FusionAuth/fusionauth-issues/issues/156
