### ISSUE TITLE
Maven central out of sync with releases and dependencies

### ISSUE THREAD

**Issue by ltj** [FusionAuth/fusionauth-java-client#3]
Hi there!

It seems maven central publications are not in sync with actual releases, but rather lagging behind a couple of versions. Furthermore, the latest java client available (as of writing), 1.17.0, has a dependency to `com.inversoft:restify:3.4.1` which is also not published, making this version fail to satisfy it's deps.

Thanks.

**Comment by robotdan** [comment]
Thanks for letting us know @ltj . 

I have fixed the missing deps. 

Regarding the client library version, we don't always release the client library for each patch release. If you are running the 1.17.0 client lib with a 1.17.x version of FusionAuth that is fine.

**Comment by ltj** [comment]
Great, thanks @robotdan
