### ISSUE TITLE
Ability to create Application level API Key

### ISSUE THREAD

**Issue by jerrybrusher** [FusionAuth/fusionauth-java-client#6]
I had verified on stackoverflow that this feature is not available and was asked to create it as a feature request in github.
Currently there is no support to create an application level API key thru java client. This feature will be very helpful when we are creating tenants/applications thru java client and we have to switch to web interface for creating api key.

**Comment by robotdan** [comment]
Thanks for opening the issue @jerrybrusher . 

Closing this one, it duplicates https://github.com/FusionAuth/fusionauth-issues/issues/887. You can track the progress under the linked issue. 

Thanks!
